### PR TITLE
PR network storage and docker-compose error

### PR DESCRIPTION
**Pull request by nitrique**
I've corrected relating to ticket #13

I found 2 bugs on the docker-compose of precedent version : docker image version was wrong and port was removed cause yml parse error.

### CODE REVIEW

**Comment by EugenMayer** [comment]
please use 1.7.8.1 not 1.7.9.0

**Comment by EugenMayer** [comment]
please define the volumes below only, if no host mount is used, see my other catalogs on how to do that

**Comment by EugenMayer** [comment]
I cannot really review the pr since you created a new version and the whole file is a diff could you please provide a pr which Rather changes 1.7.8.0 in place and then we create 1.7.8.1 in the   end..

sorry for the extra effort and thanks for the work

**Comment by nitrique** [comment]
Ok I've modified, is it ok for you ?

**Comment by EugenMayer** [comment]
the diff is great now! could you now condinitionally register the volumes only if needed, that would round it up

**Comment by nitrique** [comment]
Sorry I don't know how to do, but default values are ones used in previous version. Can you accept the PR and change by yourself ? Sorry it's monday and I have huge things to do at work :S

**Comment by EugenMayer** [comment]
Sorry, but as you have work to do, i also have such :)

You want this feature to be included and i am happy to guide you.

This is how it is done: https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci-cluster/33/docker-compose.yml.tpl#L264

Alternatively one catch match the value agains "/" and if it is included, its a host mount means, not volume is needed

This is the other part it:

https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourseci-cluster/33/docker-compose.yml.tpl#L99

**Pull request closed without merging**
