### PR TITLE
Nexus Volume Driver GUI Options

### PR DESCRIPTION
**Pull request by MrBones757**
Pretty sure the syntax on this is correct. Let me know if you need anything else.

### CODE REVIEW

**Comment by EugenMayer** [comment]
that looks good already. please remove the port expose option, I hold this as conceptually wrong that's why it's never included. you always should use a lb which then also does the ssl int interception and much more, with zero effort. thanks!

**Comment by MrBones757** [comment]
Done 👍

**Comment by EugenMayer** [comment]
very well done, no just something important
 please copy the folder 12 to 13 and be sure you create a new nexus catalog release out of that, keep 12 untouched ( since its already released )

adjust https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/sona-nexus/12/rancher-compose.yml#L3 to 3.9.0.1 ( 1 of internal release counter )

and https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/sona-nexus/config.yml#L4

as the next release pointer

then we are good to ship that one, well done!

**Comment by MrBones757** [comment]
Even though this is correct, i'm still not convinced this will work. I tried some other nexus images last night (in my late night tiredness) and they seemed to exhibit the same behavior - just hangs on startup. Will finish this and test when its released. Might have to raise an issue with them if it still doesn't work.

**Comment by MrBones757** [comment]
That should be everything now :)

**Comment by EugenMayer** [comment]
well done and thank you for your contribution, very appritiated

**Comment by EugenMayer** [comment]
@MrBones757 there seem to be an issue with this. i cannot upgrade from 12 to 13 - it hangs forever. Could you please deploy a nexus 12 and then update to 13 to see if that works for you? We need to fix that, otherwise i would need to revert hat ( i yet cannot understand why this is broken in the first place though ).

If you want to debug this, you can add your forked repo as a catalog entry so you can deploy from there until it works, then update the PR / create a new one?

**Comment by MrBones757** [comment]
Hello - I was finally able to do some investigation into this today, and have discovered that the directory you are mapping to when using persistant volumes must be owned by a user with ID 200. This documentation has been updated on the source nexus repository :)
Let me know if you need anything else

**Comment by EugenMayer** [comment]
since wit local, stacks are broken - as I have written in the issue. you did not react, so I had to  revert the feature entirely. you would need to create a new PR but test it truly, means deploy and older stack and then upgrade to the new one with type local. This does no longer boot right now, container stuck. please fix that. ensure no data / configuration is lost too

**Pull request merged**
